# -*- coding: utf-8 -*-
"""HK-MON 港精靈 — card & deck data (zh-HK / en / ja / ko)."""


def C(zh, en, ja, ko):
    return {"zh": zh, "en": en, "ja": ja, "ko": ko}


# ---------------------------------------------------------------- types -----
TYPES = {
    "fire": {
        "emoji": "🔥", "c1": "#ff6b35", "c2": "#ff9f45", "bg": "#3a1610",
        "name": C("火鍋", "Hotpot", "鍋", "훠고"),
    },
    "water": {
        "emoji": "🌊", "c1": "#38a8ff", "c2": "#7de8ff", "bg": "#0e1e33",
        "name": C("港水", "Harbour", "港", "항구"),
    },
    "grass": {
        "emoji": "🌿", "c1": "#43c96b", "c2": "#c6f68d", "bg": "#10240f",
        "name": C("山林", "Highland", "山", "산림"),
    },
    "electric": {
        "emoji": "⚡", "c1": "#ffd93d", "c2": "#fff3b0", "bg": "#2b2508",
        "name": C("雷電", "Thunder", "雷", "뇌전"),
    },
    "psychic": {
        "emoji": "🔮", "c1": "#b06bff", "c2": "#e0c3fc", "bg": "#201033",
        "name": C("靈界", "Spirit", "霊", "영계"),
    },
    "normal": {
        "emoji": "🧋", "c1": "#e8c98d", "c2": "#fff3d6", "bg": "#241f12",
        "name": C("街坊", "Street", "街", "거리"),
    },
    "trainer": {
        "emoji": "🎴", "c1": "#d4af37", "c2": "#f7e7ce", "bg": "#1d1d1d",
        "name": C("道具", "Item", "道具", "아이템"),
    },
}

TYPE_ORDER = ["fire", "water", "grass", "electric", "psychic", "normal"]

# attacker -> {defender: multiplier}
TYPE_CHART = {
    "fire":     {"grass": 1.5, "water": 0.75},
    "water":    {"fire": 1.5, "grass": 0.75},
    "grass":    {"water": 1.5, "fire": 0.75},
    "electric": {"water": 1.5},
    "psychic":  {"electric": 1.5, "psychic": 1.5},
    "normal":   {},
}


def eff_mult(atk_type, def_type):
    return TYPE_CHART.get(atk_type, {}).get(def_type, 1.0)


def weaknesses(def_type):
    """Types that hit def_type for 1.5x."""
    return [t for t, row in TYPE_CHART.items() if row.get(def_type) == 1.5]


# ---------------------------------------------------- shared basic moves ----
MOVE1 = {
    "fire": [
        {"name": C("火花四濺", "Spark Splash", "火の粉", "불똥"), "power": 10, "effect": None},
        {"name": C("辣湯彈", "Spicy Soup Ball", "スパイスボール", "마라 탄환"), "power": 14, "effect": None},
        {"name": C("炭火猛燒", "Char Grill", "炭火焼き", "숯불 구이"), "power": 16, "effect": None},
        {"name": C("麻辣燙傷", "Mala Burn", "マーラー火傷", "마라 화상"), "power": 18,
         "effect": {"status": "burn", "chance": 0.2}},
    ],
    "water": [
        {"name": C("水花彈", "Water Pop", "水しぶき", "물방울탄"), "power": 10, "effect": None},
        {"name": C("浪花沖", "Wave Rush", "波の突撃", "파도 돌진"), "power": 14, "effect": None},
        {"name": C("鹹潮浸擊", "Salty Soak", "塩水浸し", "짠물 담그기"), "power": 16, "effect": None},
        {"name": C("深水埗炸彈", "Sham Shui Po Depth Charge", "深水埗爆弾", "심수보 폭탄"), "power": 18, "effect": None},
    ],
    "grass": [
        {"name": C("落葉飛舞", "Leaf Dance", "落ち葉の舞", "낙엽 춤"), "power": 10, "effect": None},
        {"name": C("藤鞭", "Vine Snap", "つるムチ", "덩굴 채찍"), "power": 14, "effect": None},
        {"name": C("蚊叮蟲咬", "Bug Bite", "虫刺し", "모기 물기"), "power": 16, "effect": None},
        {"name": C("山泥傾瀉", "Landslide", "土砂崩れ", "산사태"), "power": 18, "effect": None},
    ],
    "electric": [
        {"name": C("叮叮充電", "Tram Charge", "トロリー充電", "딩딩 충전"), "power": 10, "effect": None},
        {"name": C("迷你閃電", "Mini Bolt", "ミニ稲妻", "미니 번개"), "power": 14, "effect": None},
        {"name": C("漏電電擊", "Leak Shock", "漏電ショック", "누전 쇼크"), "power": 16,
         "effect": {"status": "para", "chance": 0.15}},
        {"name": C("電梯急升", "Escalator Rush", "エスカ急上昇", "에스컬레이터 급상승"), "power": 18, "effect": None},
    ],
    "psychic": [
        {"name": C("銅錢占卜", "Coin Toss", "コイントス占い", "동전 점"), "power": 10, "effect": None},
        {"name": C("打麻將", "Mahjong Shuffle", "麻雀シャッフル", "마작 셔플"), "power": 14, "effect": None},
        {"name": C("靈簽一抽", "Spirit Stick Draw", "霊籤ガチャ", "영점 뽑기"), "power": 16, "effect": None},
        {"name": C("鬼遮眼", "Ghost Glare", "鬼の睨み", "귀신 눈쓰"), "power": 18,
         "effect": {"status": "para", "chance": 0.15}},
    ],
    "normal": [
        {"name": C("奶茶飛沫", "Milk Tea Splash", "ミルクティーしぶき", "밀크티 튀김"), "power": 12, "effect": None},
        {"name": C("膠叉突襲", "Fork Jab", "フォーク突き", "포크 찌르기"), "power": 14, "effect": None},
        {"name": C("菜單拍打", "Menu Slap", "メニューパチ", "메뉴판 따구기"), "power": 16, "effect": None},
        {"name": C("阿姐怒吼", "Auntie Roar", "おばちゃん怒鳴り", "아줌마 호령"), "power": 18,
         "effect": {"status": "para", "chance": 0.15}},
    ],
}

# ------------------------------------------------------------- monsters -----
# rarity: 0 = common ●, 1 = rare ★, 2 = holo ✦
# move2: cd = cooldown turns; effect optional
MONSTERS = [
    # ---------------- fire 火鍋 ----------------
    {"id": "m01", "emoji": "🍲", "type": "fire", "rarity": 2, "hp": 120,
     "name": C("火鍋牛魔王", "Hotpot Bull King", "鍋の牛魔王", "훠고 우마왕"),
     "move2": {"name": C("麻辣洪流", "Mala Torrent", "マーラー激流", "마라 격류"),
               "power": 45, "cd": 2, "effect": {"status": "burn", "chance": 0.2}},
     "flavor": C("打邊爐嘅最高境界，係連湯底都唔放過。",
                 "The ultimate hotpot master — not a drop of broth survives.",
                 "鍋の極み、スープまで飲み干す。", "훠고의 정점, 국물까지 다 마신다.")},
    {"id": "m02", "emoji": "🍚", "type": "fire", "rarity": 1, "hp": 95,
     "name": C("煲仔飯魂", "Claypot Spirit", "煲仔飯の魂", "냄비밥 혼"),
     "move2": {"name": C("臘味焦香", "Caramelized Lap Cheong", "ランプ甘香", "랍송 캐러멜"),
               "power": 38, "cd": 2, "effect": None},
     "flavor": C("一鑊靚飯焦，係香港人嘅浪漫。",
                 "Crispy rice at the bottom — a Hong Kong romance.",
                 "おこげは香港人のロマン。", "눌은밥은 홍콩인의 낭만.")},
    {"id": "m03", "emoji": "🥚", "type": "fire", "rarity": 0, "hp": 80,
     "name": C("蛋撻火焰俠", "Egg Tart Blaze", "エッグタルト炎", "에그타르트 화염"),
     "move2": {"name": C("千層酥爆", "Flaky Blast", "千層爆発", "페이스트리 폭발"),
               "power": 32, "cd": 2, "effect": None},
     "flavor": C("新鮮出爐，用心先好食。", "Fresh out of the oven, best enjoyed with heart.",
                 "焼きたてが一番。", "갓 구운 게 최고다.")},
    {"id": "m04", "emoji": "🍢", "type": "fire", "rarity": 0, "hp": 85,
     "name": C("燒賣飛彈", "Siu Mai Missile", "シウマイミサイル", "시우마이 미사일"),
     "move2": {"name": C("魚籽四射", "Roe Scatter", "卵四散", "알 사방"),
               "power": 34, "cd": 2, "effect": None},
     "flavor": C("一籠四粒，邊個都唔准搶。", "Four in a steamer — no sharing allowed.",
                 "一籠四人前、譲れない。", "한 바구니 넉 개, 양보는 금지.")},
    {"id": "m05", "emoji": "🌶️", "type": "fire", "rarity": 0, "hp": 75,
     "name": C("辣椒小霸王", "Chili Brat", "唐辛子小覇王", "고추 꼬마왕"),
     "move2": {"name": C("魔鬼辣椒水", "Devil Chili Water", "悪魔唐辛子水", "마귀 고추물"),
               "power": 30, "cd": 2, "effect": {"status": "burn", "chance": 0.25}},
     "flavor": C("唔怕辣，最怕唔夠辣。", "Never afraid of spicy — only of NOT spicy.",
                 "辛いのは怖くない、辛くないのが怖い。", "맵긴 무섭지 않다, 안 매운 게 무서워.")},
    {"id": "m06", "emoji": "🍖", "type": "fire", "rarity": 1, "hp": 110,
     "name": C("燒烤大王", "BBQ King", "バーベキュー大王", "바비큐 대왕"),
     "move2": {"name": C("蜜糖叉燒燄", "Honey Char Siu Flame", "はちみつチャーシュー炎", "꿀 차슈 불꽃"),
               "power": 44, "cd": 2, "effect": None},
     "flavor": C("半肥瘦，燒到邊緣微焦先係完美。", "Half-fat, half-lean; charred edges are perfection.",
                 "脂身半分、周りこんがりが完璧。", "반은 지방, 가장자리 살짝 탄 게 완벽.")},
    {"id": "m07", "emoji": "🍜", "type": "fire", "rarity": 0, "hp": 90,
     "name": C("車仔麵大俠", "Cart Noodle Hero", "車仔麺の侠", "차이면 협객"),
     "move2": {"name": C("十八味麻辣", "18-Spice Blast", "十八味マーラー", "18향 마라"),
               "power": 40, "cd": 2, "effect": None},
     "flavor": C("餸任揀，湯底走青多辣。", "Pick your toppings — no greens, extra spicy.",
                 "具は自由、青物抜き、辛さ多め。", "토핑 마음대로, 파 빼고, 매운맛 추가.")},
    {"id": "m08", "emoji": "🔥", "type": "fire", "rarity": 1, "hp": 105,
     "name": C("打邊爐長老", "Hotpot Elder", "鍋の長老", "훠고 장로"),
     "move2": {"name": C("滾淥辣湯", "Boiling Rage", "煮えたぎる怒り", "펄펄 끓는 분노"),
               "power": 42, "cd": 2, "effect": {"status": "burn", "chance": 0.25}},
     "flavor": C("冬天火鍋夏天冷氣，都係香港嘅命。",
                 "Hotpot in winter, AC in summer — Hong Kong's lifeline.",
                 "冬は鍋、夏は冷房、それが香港。", "겨울엔 훠고, 여름엔 에어컨, 그게 홍콩.")},
    # ---------------- water 港水 ----------------
    {"id": "m09", "emoji": "🐬", "type": "water", "rarity": 2, "hp": 115,
     "name": C("中華白海豚", "Pink Dolphin", "ピンクイルカ", "분홍돌고래"),
     "move2": {"name": C("維港飛躍", "Harbour Leap", "ビクトリア港ジャンプ", "빅토리아 항구 도약"),
               "power": 46, "cd": 2, "effect": None},
     "flavor": C("維港原居民，粉紅色嘅傳說。", "The pink legend, native of Victoria Harbour.",
                 "ビクトリア港のピンクの伝説。", "빅토리아 항구의 분홍빛 전설.")},
    {"id": "m10", "emoji": "⛴️", "type": "water", "rarity": 0, "hp": 90,
     "name": C("天星小輪俠", "Star Ferry Hero", "スターフェリーの勇者", "스타페리 용사"),
     "move2": {"name": C("渡海輪渡", "Cross-Harbour Cruise", "海峡渡航", "해협 횡단"),
               "power": 36, "cd": 2, "effect": None},
     "flavor": C("幾蚊雞過一次海，睇勻兩岸燈火。", "A few coins to cross the harbour in neon glory.",
                 "数ドルで海峡を渡り、ネオンを眺める。", "몇 달러로 항구를 건너 네온을 감상한다.")},
    {"id": "m11", "emoji": "🦐", "type": "water", "rarity": 0, "hp": 80,
     "name": C("基圍蝦將軍", "Shrimp General", "エビ将軍", "새우 장군"),
     "move2": {"name": C("彈跳蝦彈", "Shrimp Snap", "エビ弾", "새우 탄환"),
               "power": 32, "cd": 2, "effect": None},
     "flavor": C("即點即白灼，鮮到跳起。", "Boiled on order — so fresh it jumps.",
                 "注文してから茹でる、跳ねるほど新鮮。", "주문 즉시 삶는다, 뛸 만큼 신선.")},
    {"id": "m12", "emoji": "🐟", "type": "water", "rarity": 0, "hp": 70,
     "name": C("彈塗魚仔", "Mudskipper Kid", "トビハゼ", "뻘튀기"),
     "move2": {"name": C("泥漿飛濺", "Mud Splat", "泥スプラッシュ", "진흙 튀리기"),
               "power": 28, "cd": 2, "effect": None},
     "flavor": C("濕地公園跳跳紮，乜都唔驚。", "Bouncing around the wetlands, fearless.",
                 "湿地でぴょんぴょん跳ね回る。", "갯벌에서 씩씩하게 뛰어다닌다.")},
    {"id": "m13", "emoji": "🐋", "type": "water", "rarity": 2, "hp": 125,
     "name": C("維港鯨靈", "Harbour Whale", "ビクトリア港クジラ", "빅토리아 고래"),
     "move2": {"name": C("鯨尾巨浪", "Tail Tsunami", "尾びれ大波", "꼬리 해일"),
               "power": 50, "cd": 2, "effect": None},
     "flavor": C("2024 年，全城一齊送佢返屋企。", "2024: the whole city walked it home.",
                 "2024年、全市で見送った鯨。", "2024년, 도시 전체가 배웅한 고래.")},
    {"id": "m14", "emoji": "🦈", "type": "water", "rarity": 1, "hp": 100,
     "name": C("西貢鯊魚仔", "Sai Kung Shark", "サイコン鮫", "사이쿵 상어"),
     "move2": {"name": C("深海突襲", "Deep Raid", "深海急襲", "심해 급습"),
               "power": 40, "cd": 2, "effect": None},
     "flavor": C("西貢碼頭唔使問，魚蛋先係老大。", "At Sai Kung pier, fishballs rule the waves.",
                 "西貢埠頭の主は魚団子。", "사이쿵 부두의 왕은 어완이다.")},
    {"id": "m15", "emoji": "🌊", "type": "water", "rarity": 1, "hp": 95,
     "name": C("東江水龍", "Dongjiang Dragon", "東江水の龍", "둥장수 용"),
     "move2": {"name": C("東江之水夜奔", "West Water Surge", "東江水の奔流", "둥장수 격류"),
               "power": 38, "cd": 2, "effect": None},
     "flavor": C("一江清水向港流，六十年唔斷。", "Sixty years of fresh water flowing to Hong Kong.",
                 "60年間、香港へ水を届ける。", "60년간 홍콩으로 물을 실어 온 강.")},
    {"id": "m16", "emoji": "🐙", "type": "water", "rarity": 0, "hp": 85,
     "name": C("八爪魚墨俠", "Octopus Ink", "タコの墨侠", "문어 먹 협객"),
     "move2": {"name": C("墨汁煙幕", "Ink Screen", "墨煙幕", "먹 연막"),
               "power": 30, "cd": 2, "effect": {"status": "para", "chance": 0.2}},
     "flavor": C("避風塘一帶，邊度都走得甩。", "Around the typhoon shelter, there is always an escape.",
                 "避風塘ならどこでも逃げられる。", "태풍 항만이면 어디든 도망친다.")},
    # ---------------- grass 山林 ----------------
    {"id": "m17", "emoji": "🦁", "type": "grass", "rarity": 2, "hp": 120,
     "name": C("獅子山靈", "Lion Rock Spirit", "ライオンロックの精霊", "사자바위 영"),
     "move2": {"name": C("獅子山精神", "Lion's Roar", "ライオンロックの咆哮", "사자 포효"),
               "power": 46, "cd": 2, "effect": {"buff": 10}},
     "flavor": C("獅子山下，同舟共濟。", "Below Lion Rock, we row together.",
                 "獅子山の下、同じ船に乗る。", "사자산 아래, 한 배를 탄다.")},
    {"id": "m18", "emoji": "⛰️", "type": "grass", "rarity": 0, "hp": 90,
     "name": C("太平山霧精", "Peak Mist Sprite", "ピークの霧", "빅토리아 피크 안개"),
     "move2": {"name": C("山頂濃霧", "Peak Fog", "山頂の濃霧", "산정 안개"),
               "power": 32, "cd": 2, "effect": {"status": "para", "chance": 0.2}},
     "flavor": C("山頂纜車搖下搖下，就到凌霄閣。", "The Peak Tram wobbles all the way up to the Tower.",
                 "ピークトラムがゆらゆら登る。", "피크 트램이 흔들흔들 올라간다.")},
    {"id": "m19", "emoji": "🧘", "type": "grass", "rarity": 2, "hp": 130,
     "name": C("天壇大佛", "Big Buddha", "天壇大仏", "천단 대불"),
     "move2": {"name": C("佛光普照", "Buddha's Light", "仏光普照", "불광 보현"),
               "power": 42, "cd": 2, "effect": {"heal_pct": 0.2}},
     "flavor": C("大嶼山一日遊，記得食齋先夠數。", "A day on Lantau isn't complete without the vegetarian meal.",
                 "大嶼山の締めは精進料理。", "란터우 하루는 채식으로 마무리.")},
    {"id": "m20", "emoji": "🦌", "type": "grass", "rarity": 0, "hp": 80,
     "name": C("八仙嶺小鹿", "Pat Sin Leng Fawn", "八仙嶺の鹿", "팔선령 사슴"),
     "move2": {"name": C("仙嶺飛踢", "Celestial Kick", "八仙嶺キック", "팔선령 킥"),
               "power": 30, "cd": 2, "effect": None},
     "flavor": C("八仙嶺行山，記得帶夠水。", "Hiking Pat Sin Leng — bring enough water.",
                 "八仙嶺登山は水を忘れずに。", "팔선령 등산, 물 꼭 챙겨라.")},
    {"id": "m21", "emoji": "🐃", "type": "grass", "rarity": 1, "hp": 110,
     "name": C("城門水牛", "Shing Mun Buffalo", "城門の水牛", "성문 물소"),
     "move2": {"name": C("水牛衝撞", "Buffalo Charge", "水牛タックル", "물소 돌진"),
               "power": 40, "cd": 2, "effect": None},
     "flavor": C("城門水塘原居民，慢活之王。", "The slow-living king of Shing Mun Reservoir.",
                 "城門水塘のんびり大王。", "성문 저수지의 느긋한 왕.")},
    {"id": "m22", "emoji": "🦅", "type": "grass", "rarity": 0, "hp": 85,
     "name": C("米埔候鳥", "Mai Po Migrant", "米埔の渡り鳥", "마이포 철새"),
     "move2": {"name": C("千里南遷", "Great Migration", "長距離渡り", "천리 남하"),
               "power": 34, "cd": 2, "effect": None},
     "flavor": C("每年冬天，準時返嚟過冬。", "Every winter, back right on time.",
                 "毎年冬、時間通りに帰る。", "매년 겨울, 시간 딱 맞춰 돌아온다.")},
    {"id": "m23", "emoji": "🌳", "type": "grass", "rarity": 1, "hp": 105,
     "name": C("榕樹頭伯伯", "Banyan Elder", "ガジュマルの翁", "반야수 노인"),
     "move2": {"name": C("氣根纏繞", "Root Bind", "気根絡み", "기근 감기"),
               "power": 36, "cd": 2, "effect": {"status": "para", "chance": 0.25}},
     "flavor": C("榕樹頭下，講古論今。", "Under the banyan tree — stories old and new.",
                 "ガジュマルの下で昔語り。", "반야수 아래 이야기 한 판.")},
    {"id": "m24", "emoji": "🐼", "type": "grass", "rarity": 1, "hp": 100,
     "name": C("熊貓滾滾", "Panda Roll", "パンダロール", "판다 꿀렁"),
     "move2": {"name": C("竹筒滾山", "Bamboo Roll", "竹ローラー", "대나무 굴리기"),
               "power": 38, "cd": 2, "effect": None},
     "flavor": C("海洋公園一哥，食飽就瞓。", "Ocean Park's boss — eat, then nap.",
                 "オーシャンパークのボス、食べて寝る。", "오션파크의 보스, 먹고 자기.")},
    # ---------------- electric 雷電 ----------------
    {"id": "m25", "emoji": "🚋", "type": "electric", "rarity": 1, "hp": 95,
     "name": C("叮叮俠", "Ding Ding Hero", "ディンディン侠", "딩딩 히어로"),
     "move2": {"name": C("雙層衝線", "Double-Deck Charge", "二階建て突撃", "2층 돌진"),
               "power": 40, "cd": 2, "effect": {"status": "para", "chance": 0.2}},
     "flavor": C("全港最平觀光巴士，六舊幾行勻港島。", "The cheapest sightseeing tour on Hong Kong Island.",
                 "香港島を6ドルで巡る最安ツアー。", "홍콩섬을 6달러에 돌아보는 최저가 투어.")},
    {"id": "m26", "emoji": "🚐", "type": "electric", "rarity": 1, "hp": 100,
     "name": C("紅Van車神", "Red Van Legend", "赤バンの神様", "빨간 승합차 신"),
     "move2": {"name": C("紅Van漂移", "Red Van Drift", "赤バンドリフト", "빨강밴 드리프트"),
               "power": 44, "cd": 2, "effect": None},
     "flavor": C("到站先會停，全靠一個「快」字。", "It stops when it stops — speed is everything.",
                 "止まる時は止まる、速さが全て。", "서야 할 때 서고, 빠름이 전부다.")},
    {"id": "m27", "emoji": "🚕", "type": "electric", "rarity": 0, "hp": 90,
     "name": C("的士大佬", "Taxi Master", "タクシーの兄貴", "택시 형님"),
     "move2": {"name": C("跳錶狂奔", "Meter Runner", "メーター狂奔", "미터기 질주"),
               "power": 38, "cd": 2, "effect": None},
     "flavor": C("紅磡去中環，唔行隧道就得閒吓。", "Hung Hom to Central — taking the long way, no rush.",
                 "紅磡から中環、トンネル使わず余裕。", "훙좜에서 중환까지, 터널 안 쓰고 여유.")},
    {"id": "m28", "emoji": "🚇", "type": "electric", "rarity": 1, "hp": 110,
     "name": C("港鐵靈", "MTR Spirit", "MTRの霊", "MTR 영"),
     "move2": {"name": C("月台衝擊", "Platform Rush", "ホームラッシュ", "승강장 러시"),
               "power": 42, "cd": 2, "effect": {"status": "para", "chance": 0.2}},
     "flavor": C("請勿靠近車門，多謝合作。", "Please stand clear of the doors.",
                 "ドアから離れてお待ちください。", "문에서 비켜 주십시오.")},
    {"id": "m29", "emoji": "🛗", "type": "electric", "rarity": 0, "hp": 85,
     "name": C("半山電梯龍", "Escalator Dragon", "エスカレータードラゴン", "에스컬레이터 드래곤"),
     "move2": {"name": C("中環扶搖", "Central Ascent", "中環上昇", "중환 상승"),
               "power": 34, "cd": 2, "effect": None},
     "flavor": C("全球最長扶梯，朝早落山夜晚上山。", "World's longest escalator — downhill by day, uphill by night.",
                 "世界最長、昼は下り夜は上り。", "세계 최장, 낮엔 내리고 밤엔 오른다.")},
    {"id": "m30", "emoji": "💳", "type": "electric", "rarity": 1, "hp": 95,
     "name": C("八達通精靈", "Octopus Card Sprite", "オクトパスカード", "옥토퍼스 카드"),
     "move2": {"name": C("一拍即付", "Tap & Go", "タップ決済", "탭 결제"),
               "power": 36, "cd": 2, "effect": {"buff": 8}},
     "flavor": C("一嘟過閘，連雪糕車都嘟到。", "Beep through the gate — even pays the ice cream van.",
                 "ピッと改札、アイスクリーム車でも使える。", "삑! 개찰구도, 아이스크림 트럭도.")},
    {"id": "m31", "emoji": "🌃", "type": "electric", "rarity": 0, "hp": 90,
     "name": C("霓虹招牌獸", "Neon Sign Beast", "ネオンサイン獣", "네온 사인 수"),
     "move2": {"name": C("霓虹閃爆", "Neon Burst", "ネオン爆発", "네온 폭발"),
               "power": 38, "cd": 2, "effect": {"status": "burn", "chance": 0.2}},
     "flavor": C("街邊塊霓虹招牌，閃足三十年。", "That street-side neon has flickered for 30 years.",
                 "街角のネオン、30年点滅中。", "길거리 네온사인, 30년째 깜빡임.")},
    {"id": "m32", "emoji": "🍦", "type": "electric", "rarity": 0, "hp": 80,
     "name": C("雪糕車伯伯", "Mister Softy", "ソフトクリーム車", "아이스크림 트럭 아저씨"),
     "move2": {"name": C("軟雪糕旋風", "Softcream Spin", "ソフトクリーム旋風", "소프트크림 회오리"),
               "power": 32, "cd": 2, "effect": None},
     "flavor": C("音樂一響，全條街啲細路都衝出嚟。", "One tune, and every kid on the street storms out.",
                 "音楽で子供大集合。", "음악이 흐르면 아이들 전원 출동.")},
    # ---------------- psychic 靈界 ----------------
    {"id": "m33", "emoji": "🐉", "type": "psychic", "rarity": 2, "hp": 130,
     "name": C("大坑舞火龍", "Tai Hang Fire Dragon", "大坑の火龍", "타이항 화룡"),
     "move2": {"name": C("火龍過市", "Tai Hang Inferno", "火龍行進", "화룡 행진"),
               "power": 52, "cd": 2, "effect": {"status": "burn", "chance": 0.25}},
     "flavor": C("中秋大坑，龍過之處，蚊都冇埋。", "Where the fire dragon passes, even mosquitoes flee.",
                 "龍が通れば蚊も消える。", "용이 지나가면 모기도 사라진다.")},
    {"id": "m34", "emoji": "🥠", "type": "psychic", "rarity": 1, "hp": 100,
     "name": C("長洲包山靈", "Bun Tower Spirit", "パン山の精", "만산 영"),
     "move2": {"name": C("搶包山", "Bun Scramble", "パン争奪", "빵 타기"),
               "power": 40, "cd": 2, "effect": None},
     "flavor": C("搶到包山王，全年都平安。", "Win the bun scramble, stay safe all year.",
                 "パン山の王者は一年安全。", "빵산 왕이면 1년 무탈.")},
    {"id": "m35", "emoji": "🀄", "type": "psychic", "rarity": 1, "hp": 110,
     "name": C("麻將雀神", "Mahjong God", "雀神", "작신"),
     "move2": {"name": C("十三幺", "Thirteen Orphans", "国士無双", "십삼요"),
               "power": 48, "cd": 2, "effect": {"status": "para", "chance": 0.2}},
     "flavor": C("你咪住，等我摸咗先講。", "Hold on — let me draw first.",
                 "待って、先に引かせて。", "기다려, 내가 먼저 뽑을게.")},
    {"id": "m36", "emoji": "🔮", "type": "psychic", "rarity": 0, "hp": 85,
     "name": C("廟街算命佬", "Temple St. Fortune Teller", "廟街の占い師", "묘가 점술가"),
     "move2": {"name": C("命運改寫", "Fate Twist", "運命改変", "운명 개쓰기"),
               "power": 34, "cd": 2, "effect": {"heal_pct": 0.15}},
     "flavor": C("睇相三十蚊，包你逢賭必贏——講吓啫。", "Palm reading $30 — guarantees every bet. Allegedly.",
                 "手相300円、必勝……たぶん。", "관상 3만 원, 노름 무조건 이긴다……아마.")},
    {"id": "m37", "emoji": "🧧", "type": "psychic", "rarity": 1, "hp": 95,
     "name": C("財神爺到", "Fortune God", "財神様", "재신"),
     "move2": {"name": C("派利是", "Red Packet Rain", "お年玉シャワー", "세뱃돈 소나기"),
               "power": 36, "cd": 2, "effect": {"buff": 10}},
     "flavor": C("逗利是要講意頭：恭喜發財！", "Say the magic words: Kung Hei Fat Choy!",
                 "意頭大事やで、ゴンキーファーチョイ！", "덕담은 필수: 공희발채!")},
    {"id": "m38", "emoji": "🐰", "type": "psychic", "rarity": 0, "hp": 80,
     "name": C("中秋玉兔", "Moon Rabbit", "月の兎", "달토끼"),
     "move2": {"name": C("月光棒擊", "Moonlight Whack", "月光バット", "달빛 방망이"),
               "power": 32, "cd": 2, "effect": None},
     "flavor": C("維園花燈下，陪嫦娥守到半夜。", "Under the Victoria Park lanterns, guarding till midnight.",
                 "ビクトリアパークの灯籠の下で。", "빅토리아 공원 등불 아래서.")},
    {"id": "m39", "emoji": "🧟", "type": "psychic", "rarity": 0, "hp": 90,
     "name": C("殭屍小鬼", "Little Jiangshi", "キョンシー小僧", "강시 꼬마"),
     "move2": {"name": C("屍跳嚇人", "Hop Scare", "キョンシージャンプ", "강시 점프"),
               "power": 34, "cd": 2, "effect": {"status": "para", "chance": 0.25}},
     "flavor": C("一手一個道符，半夜唔准出街。", "Hold the talisman — no going out at night.",
                 "お札を持って夜は出るな。", "부적 들고 밤엔 나가지 마.")},
    {"id": "m40", "emoji": "🏮", "type": "psychic", "rarity": 1, "hp": 95,
     "name": C("觀音靈簽", "Kwun Yum Oracle", "観音霊籤", "관음 영점"),
     "move2": {"name": C("上上籤", "Great Fortune", "大吉籤", "대긴 점"),
               "power": 38, "cd": 2, "effect": {"heal_pct": 0.15}},
     "flavor": C("求得中吉，心安自然靈。", "A middle-luck stick is enough — peace of mind works.",
                 "中吉で十分、心安らかに。", "중길이면 충분, 마음 편하면 다 잘 된다.")},
    # ---------------- normal 街坊 ----------------
    {"id": "m41", "emoji": "🍛", "type": "normal", "rarity": 0, "hp": 90,
     "name": C("茶餐廳伙記", "Cha Chaan Waiter", "茶餐庁ウェイター", "차찬텡 웨이터"),
     "move2": {"name": C("快餐旋風", "Fast Food Whirl", "ファストフード旋風", "패스트푸드 회오리"),
               "power": 34, "cd": 2, "effect": None},
     "flavor": C("快靚正，三十秒上齊全部嘢。", "Fast, good, cheap — everything lands in 30 seconds.",
                 "速くて旨くて安い、30秒で全部。", "빠르고 맛있고 싸다, 30초면 전부 나온다.")},
    {"id": "m42", "emoji": "👵", "type": "normal", "rarity": 0, "hp": 85,
     "name": C("唐樓阿婆", "Tenement Granny", "唐楼のお婆ちゃん", "통로우 아줌마"),
     "move2": {"name": C("買餸菜籃", "Market Basket", "買い物かご", "장바구니 휘두르기"),
               "power": 32, "cd": 2, "effect": {"status": "para", "chance": 0.2}},
     "flavor": C("落雨收衫落街買餸，一嚿氣搞掂。", "Grab the laundry, buy dinner — all in one go.",
                 "雨なら洗濯物、街へ買い物、一気にこなす。", "비 오면 빨래 거두고 장 보고, 한 번에 끝.")},
    {"id": "m43", "emoji": "🐟", "type": "normal", "rarity": 1, "hp": 95,
     "name": C("街市魚佬", "Fishmonger", "市場の魚屋", "시장 생선 아저씨"),
     "move2": {"name": C("劏魚快斬", "Fish Chop", "魚さばき", "생선 손질"),
               "power": 40, "cd": 2, "effect": None},
     "flavor": C("你睇下條魚幾新鮮，眼都未閉。", "Look how fresh — the fish hasn't even blinked.",
                 "見てこの新鮮さ、まだ目が開いてる。", "봐라 이 신선함, 아직 눈도 안 감았어.")},
    {"id": "m44", "emoji": "🚌", "type": "normal", "rarity": 1, "hp": 100,
     "name": C("巴士阿叔", "Bus Uncle", "バスのおっちゃん", "버스 아저씨"),
     "move2": {"name": C("壓力怒吼", "Pressure Roar", "プレッシャー咆哮", "스트레스 포효"),
               "power": 38, "cd": 2, "effect": {"status": "para", "chance": 0.25}},
     "flavor": C("你有壓力，我有壓力，你做咩挑釁我呀？",
                 "You have pressure, I have pressure — why provoke me?!",
                 "君にも俺にもプレッシャーがある。", "너도 스트레스, 나도 스트레스!")},
    {"id": "m45", "emoji": "🎒", "type": "normal", "rarity": 0, "hp": 75,
     "name": C("學生哥", "School Kid", "学生ちゃん", "학생"),
     "move2": {"name": C("溫書轟炸", "Study Beam", "勉強ビーム", "공부 빔"),
               "power": 30, "cd": 2, "effect": None},
     "flavor": C("測驗啱啱完，即刻走去睇戲。", "Test just ended — straight to the movies.",
                 "テスト終わり、映画に直行。", "시험 끝, 바로 영화관으로.")},
    {"id": "m46", "emoji": "💼", "type": "normal", "rarity": 0, "hp": 85,
     "name": C("OT王", "OT King", "残業王", "야근왕"),
     "move2": {"name": C("加班怨氣", "OT Grudge", "残業の怨念", "야근 원념"),
               "power": 36, "cd": 2, "effect": {"status": "burn", "chance": 0.2}},
     "flavor": C("放工？香港邊有放工呢樣嘢。", "Off work? What's that in Hong Kong?",
                 "退勤？香港にそんなものはない。", "퇴근? 홍콩에 그런 게 있어?")},
    {"id": "m47", "emoji": "💊", "type": "normal", "rarity": 0, "hp": 90,
     "name": C("藥房阿姐", "Pharmacy Sis", "薬房のお姉さん", "약방 언니"),
     "move2": {"name": C("白花油點睛", "Medicated Oil Touch", "白花油ツーン", "백화유 찔르기"),
               "power": 34, "cd": 2, "effect": {"heal_pct": 0.15}},
     "flavor": C("頭暈身慶？一滴白花油即刻醒神。", "Dizzy? One drop of medicated oil — instantly awake.",
                 "めまい？白花油一滴で即スッキリ。", "어지럽다? 백화유 한 방울이면 정신 번쩍.")},
    {"id": "m48", "emoji": "📮", "type": "normal", "rarity": 1, "hp": 95,
     "name": C("郵差叔叔", "Postman Uncle", "郵便屋さん", "우체부 아저씨"),
     "move2": {"name": C("掛號急件", "Registered Rush", "書留ダッシュ", "등기 급송"),
               "power": 38, "cd": 2, "effect": None},
     "flavor": C("風球都照派，信件準時到。", "Typhoon or not, the mail arrives on time.",
                 "台風でも配達は時間通り。", "태풍이 와도 우편은 제시간에.")},
]

MON = {m["id"]: m for m in MONSTERS}

# ---------------------------------------------------------------- items -----
ITEMS = [
    {"id": "i01", "emoji": "🧋", "effect": {"kind": "heal", "n": 45},
     "name": C("絲襪奶茶", "Silk-Stocking Milk Tea", "ストッキングミルクティー", "스타킹 밀크티"),
     "desc": C("回復 45 HP。", "Restore 45 HP.", "HPを45回復。", "HP 45 회복.")},
    {"id": "i02", "emoji": "🍍", "effect": {"kind": "buff", "n": 12},
     "name": C("菠蘿油", "Pineapple Bun w/ Butter", "ボーローバター", "파인애플번 버터"),
     "desc": C("下一次攻擊 +12 傷害。", "Next attack deals +12 damage.", "次の攻撃のダメージ+12。", "다음 공격 피해 +12.")},
    {"id": "i03", "emoji": "🧇", "effect": {"kind": "shield"},
     "name": C("雞蛋仔盾", "Egg Waffle Shield", "エッグワッフル盾", "계란빵 방패"),
     "desc": C("下一次受創減半。", "Take half damage from the next hit.", "次に受けるダメージ半減。", "다음 받는 피해 절반.")},
    {"id": "i04", "emoji": "🍵", "effect": {"kind": "cure", "n": 15},
     "name": C("廿四味涼茶", "24-Herb Herbal Tea", "二十四味涼茶", "이십사미 한차"),
     "desc": C("醫好所有狀態，並回復 15 HP。", "Cure all status and restore 15 HP.", "状態を治し、HPを15回復。", "상태를 치료하고 HP 15 회복.")},
    {"id": "i05", "emoji": "🍢", "effect": {"kind": "reset_cd", "n": 10},
     "name": C("魚蛋精力串", "Fishball Power Skewer", "魚団子串", "어완 꼬치"),
     "desc": C("招式冷卻重置，並回復 10 HP。", "Reset move cooldowns and restore 10 HP.", "技のクールダウンをリセットし、HPを10回復。", "기술 재사용 대기시간 초기화, HP 10 회복.")},
    {"id": "i06", "emoji": "🚨", "effect": {"kind": "para_enemy"},
     "name": C("八號風球", "Signal No. 8", "台風シグナル8", "8호 풍구"),
     "desc": C("令對手的精靈麻痺。", "Paralyze the opponent's active card.", "相手のバトルポケモンを麻痺させる。", "상대 카드를 마비시킨다.")},
    {"id": "i07", "emoji": "📢", "effect": {"kind": "force_switch"},
     "name": C("的士喇叭", "Taxi Horn Blast", "タクシークラクション", "택시 클랙슨"),
     "desc": C("嚇得對手被迫換精靈。", "Force the opponent to switch.", "相手を強制交代させる。", "상대를 강제 교체시킨다.")},
    {"id": "i08", "emoji": "🎯", "effect": {"kind": "direct", "n": 25},
     "name": C("飛魚蛋擲擊", "Fishball Throw", "魚団投げ", "어완 던지기"),
     "desc": C("直接對對手造成 25 點傷害。", "Deal 25 direct damage to the opponent.", "相手に直接25ダメージ。", "상대에게 직접 25 피해.")},
    {"id": "i09", "emoji": "🧧", "effect": {"kind": "bench_heal", "n": 20},
     "name": C("老細利是", "Boss's Red Packet", "ボスのお年玉", "사장님 세뱃돈"),
     "desc": C("後備精靈全部回復 20 HP。", "Heal all your bench cards by 20 HP.", "ベンチ全員のHPを20回復。", "후보 전원 HP 20 회복.")},
    {"id": "i10", "emoji": "🎫", "effect": {"kind": "add_cd_enemy", "n": 1},
     "name": C("MTR故障通知", "MTR Delay Notice", "MTR遅延通知", "MTR 지연 통지"),
     "desc": C("對手招式冷卻 +1 回合。", "Opponent's cooldowns +1 turn.", "相手の技の遅延+1ターン。", "상대 기술 대기시간 +1턴.")},
    {"id": "i11", "emoji": "🧊", "effect": {"kind": "heal_cure_burn", "n": 25},
     "name": C("凍檸茶", "Iced Lemon Tea", "アイスレモンティー", "아이스 레몬티"),
     "desc": C("回復 25 HP 並醫好燒傷。", "Restore 25 HP and cure burn.", "HPを25回復し、やけどを治す。", "HP 25 회복, 화상 치료.")},
    {"id": "i12", "emoji": "🍚", "effect": {"kind": "heal", "n": 70},
     "name": C("叉燒飯大件夾抵食", "BBQ Pork Rice Feast", "チャーシューご飯", "차슈밥 대사"),
     "desc": C("大回復 70 HP，一場一次。", "Restore 70 HP — once per battle.", "HPを70回復、1戦1回。", "HP 70 회복, 전투당 1회.")},
]

ITEM = {i["id"]: i for i in ITEMS}

# set numbers: monsters 1-48, items 49-60
SET_NO = {}
for _i, _m in enumerate(MONSTERS):
    SET_NO[_m["id"]] = _i + 1
for _i, _it in enumerate(ITEMS):
    SET_NO[_it["id"]] = 49 + _i

# ---------------------------------------------------------------- decks -----
DECKS = [
    {"id": "d1", "emoji": "🍜", "mons": ["m41", "m42", "m43", "m44", "m47"], "items": ["i01", "i02", "i04"],
     "name": C("茶餐廳同盟", "Cha Chaan Teng Alliance", "茶餐庁同盟", "차찬텡 동맹"),
     "desc": C("快靚正街坊兵團，穩打穩紮。", "Fast, good, cheap — solid neighbourhood crew.",
               "速くて旨くて安い、街の精鋭。", "빠르고 맛있고 싼 동네 정예부대.")},
    {"id": "d2", "emoji": "🌊", "mons": ["m09", "m10", "m13", "m15", "m16"], "items": ["i01", "i05", "i08"],
     "name": C("維港水軍", "Victoria Harbour Fleet", "ビクトリア港艦隊", "빅토리아 함대"),
     "desc": C("維港海軍，浪裡稱王。", "Masters of the harbour waves.", "港の波の王者。", "빅토리아 항구의 파도의 왕.")},
    {"id": "d3", "emoji": "🍲", "mons": ["m01", "m02", "m06", "m07", "m08"], "items": ["i02", "i11", "i12"],
     "name": C("火鍋兵團", "Hotpot Legion", "鍋軍団", "훠고 군단"),
     "desc": C("麻辣係浪漫，燒傷係 bonus。", "Spicy is romance; burns are a bonus.",
               "辛さはロマン、やけどはボーナス。", "매운맛은 낭만, 화상은 보너스.")},
    {"id": "d4", "emoji": "🦁", "mons": ["m17", "m19", "m21", "m23", "m24"], "items": ["i03", "i04", "i05"],
     "name": C("獅子山守衛", "Lion Rock Guard", "ライオンロック衛兵", "사자산 수비대"),
     "desc": C("高山厚血，同舟共濟。", "Thick mountain HP — we row together.",
               "高いHP、同じ船に乗る。", "높은 HP, 한 배를 탄다.")},
    {"id": "d5", "emoji": "🚋", "mons": ["m25", "m26", "m27", "m28", "m30"], "items": ["i02", "i07", "i11"],
     "name": C("電光快線", "Electric Express", "エレクトリック急行", "전광쾌선"),
     "desc": C("紅Van漂移，麻痺快攻。", "Red Van drift — fast paralysis offense.",
               "赤バンドリフト、麻痺速攻。", "빨강밴 드리프트, 마비 속공.")},
    {"id": "d6", "emoji": "🐉", "mons": ["m33", "m34", "m35", "m36", "m40"], "items": ["i06", "i08", "i12"],
     "name": C("廟街夜神", "Temple Street Nights", "廟街の夜神", "묘가의 밤신"),
     "desc": C("火龍過市，靈界之王。", "The fire dragon rules the night.", "火龍は夜の王。", "화룡은 밤의 왕.")},
    {"id": "d7", "emoji": "🧋", "mons": ["m01", "m17", "m25", "m33", "m41"], "items": ["i01", "i03", "i06"],
     "name": C("街坊大雜燴", "Neighbourhood Mix-up", "街角ミックス", "동네 잡탕"),
     "desc": C("五行齋菜，乜都有啲。", "One of each type — a bit of everything.",
               "五行バランス型。", "다섯 속성 골고루.")},
    {"id": "d8", "emoji": "🎲", "random": True, "mons": [], "items": [],
     "name": C("驚喜盲盒隊", "Mystery Box Squad", "ミステリーボックス", "미스터리 박스"),
     "desc": C("每場隨機抽 5 隻精靈 + 3 件道具。", "Random 5 cards + 3 items every battle.",
               "毎試合ランダム編成。", "매 전투마다 무작위 편성.")},
    {"id": "d9", "emoji": "👑", "hidden": True, "mons": ["m33", "m17", "m13", "m35", "m01"], "items": ["i06", "i02", "i12"],
     "name": C("終極港靈王", "Ultimate HK-Mon King", "アルティメット王", "얼티밋 홍콩왕"),
     "desc": C("三連霸最終關，全明星敵隊。", "Gauntlet final — the all-star enemy squad.",
               "三連戦の最終関門。", "3연전 최종 관문.")},
]

DECK = {d["id"]: d for d in DECKS}
CHOOSABLE_DECKS = [d for d in DECKS if not d.get("hidden")]
GAUNTLET = ["d5", "d3", "d9"]

TOTAL_CARDS = len(MONSTERS) + len(ITEMS)  # 60


def all_cards():
    """Unified card list for the library: dicts with kind field."""
    out = []
    for m in MONSTERS:
        c = dict(m)
        c["kind"] = "mon"
        out.append(c)
    for it in ITEMS:
        c = dict(it)
        c["kind"] = "item"
        c["rarity"] = 1
        out.append(c)
    return out
